// Past shows, newest first.
// Sourced from Resident Advisor (ra.co/dj/ricocasazza/past-events) and
// Instagram (@ricocasazza_music) for dates RA doesn't cover.
export const pastShows = [
  { date: '2026-07-17', event: 'Compact Disco: Festival ~ Year Zero', location: 'Prague, Czech Republic' },
  { date: '2026-03-07', event: 'Live at Piękny Pies (live debut)', location: 'Kraków, Poland' },
  { date: '2026-02-01', event: 'House & Bounce', location: 'Mumbai, India' },
  { date: '2026-01-30', event: 'Singularity Takeover — The Up, Koh Rong Island', location: 'Koh Rong Island, Cambodia' },
  { date: '2026-01-28', event: 'Big Easy', location: 'Phnom Penh, Cambodia' },
  { date: '2026-01-24', event: 'Groove & Cruise (Desert Disco Shifi)', location: 'Phnom Penh, Cambodia' },
  { date: '2026-01-23', event: 'Singularity — Sundown Social Club', location: 'Phnom Penh, Cambodia' },
  { date: '2026-01-11', event: 'Live at Bangkok Community Radio', location: 'Bangkok, Thailand' },
  { date: '2026-01-07', event: '12x12bkk', location: 'Bangkok, Thailand' },
  { date: '2025-12-31', event: "New Year's Eve — The Bar Room Thamel", location: 'Kathmandu, Nepal' },
  { date: '2025-12-25', event: 'Mixmaam', location: 'Kathmandu, Nepal' },
  { date: '2025-12-19', event: 'Kittenpop — Amber Cocktail Bar', location: 'Goa, India' },
  { date: '2025-12-06', event: 'Amber Cocktail Bar', location: 'Goa, India' },
  { date: '2025-12-05', event: 'Kittenpop Experience', location: 'Mumbai, India' },
  { date: '2025-11-30', event: 'Kittenpop.love', location: 'Mumbai, India' },
  { date: '2025-11-29', event: 'Kittenpop — Indiranagar Social', location: 'Bangalore, India' },
  { date: '2025-11-29', event: 'Ableton Workshop', location: 'Bangalore, India' },
  { date: '2025-11-22', event: 'Kittenpop — ext.hyd', location: 'Hyderabad, India' },
  { date: '2025-11-21', event: 'Mircommune', location: 'Goa, India' },
  { date: '2025-06-17', event: 'Netil Radio: Fear of Music', location: 'London, UK' },
  { date: '2025-06-14', event: 'RA 17th Anniversary: Boat Party & Afterparty at EGG', location: 'London, UK' },
  { date: '2025-06-13', event: 'Hoxton Hotel', location: 'London, UK' },
  { date: '2025-05-31', event: 'NASTY! #4: Day & Night', location: 'Prague, Czech Republic' },
  { date: '2025-05-23', event: 'Gram Records 8th Anniversary', location: 'Prague, Czech Republic' },
  { date: '2025-04-26', event: 'Moving Pictures — djs Rico Casazza, Roman Rai, TÄINO', location: 'Prague, Czech Republic' },
  { date: '2025-04-26', event: 'LBD Sounds: Rico 909 Release Meeting', location: 'Prague, Czech Republic' },
  { date: '2025-04-12', event: 'RA: Rico Casazza, Z-Kat, Sam Gittis, Thomas Tesla over 3 floors', location: 'Prague, Czech Republic' },
  { date: '2024-11-29', event: 'Bud x Kittenpop Weekender Goa', location: 'Goa, India' },
  { date: '2024-11-23', event: 'Kittenpop Experience', location: 'Mumbai, India' },
  { date: '2024-09-28', event: 'RA: Rico Casazza, Thomas Tesla, and many more over 3 floors', location: 'Prague, Czech Republic' },
  { date: '2024-09-06', event: 'Moving Pictures: The Labyrinth', location: 'Prague, Czech Republic' },
  { date: '2024-08-31', event: 'Loose Movement — djs Rico Casazza, TÄINO, Ezwell', location: 'Prague, Czech Republic' },
  { date: '2024-07-20', event: "RA: Rico Casazza, Z-Kat, 90'z and many more over 3 floors", location: 'Prague, Czech Republic' },
  { date: '2024-06-08', event: 'RA Boat Party & Afterparty at Ministry Of Sound 16th Anniversary', location: 'London, UK' },
  { date: '2024-04-27', event: 'Boat Party: Gram Records x Republic Artists & Afterparty', location: 'Prague, Czech Republic' },
  { date: '2024-03-16', event: 'Tendancedance with Rico Casazza & Kozber', location: 'Prague, Czech Republic' },
  { date: '2024-02-24', event: 'RA: Rico Casazza, Elektrabel, Riki Boro, TÄINO, Stessie over 3 floors', location: 'Prague, Czech Republic' },
  { date: '2024-02-03', event: 'Moving Pictures — djs Rico Casazza, Roman Rai, TÄINO', location: 'Prague, Czech Republic' },
  { date: '2023-11-18', event: 'DGTL Mumbai 2023', location: 'Mumbai, India' },
  { date: '2023-09-16', event: 'RA: Rico Casazza, Elektrabel, Unjack, Lillou, Thomas Tesla, Icarian PB1, Koka', location: 'Prague, Czech Republic' },
  { date: '2023-08-27', event: 'Republic Artists: Back to The River Thames', location: 'London, UK' },
  { date: '2023-08-18', event: 'Moving Pictures — djs Rico Casazza, TÄINO, Ezwell', location: 'Prague, Czech Republic' },
  { date: '2023-07-22', event: 'Loose Movements Night visits Bukanyr Boat — djs Kozber, Rico Casazza, Kube', location: 'Prague, Czech Republic' },
  { date: '2023-07-15', event: 'Republic Artists: Rico Casazza, Kozber, Lucas Hulan, Thomas Tesla over 3 floors', location: 'Prague, Czech Republic' },
  { date: '2023-05-27', event: 'DT pres. Rico Casazza + Garden Opening', location: 'Poznan, Poland' },
  { date: '2023-05-26', event: 'MIKRO', location: 'Berlin, Germany' },
  { date: '2023-04-21', event: 'Nu Spirit Bar presents Rico Casazza & wnchnz', location: 'Bratislava, Slovakia' },
  { date: '2023-03-31', event: 'Cross x Afterhours', location: 'Prague, Czech Republic' },
  { date: '2023-03-18', event: "Republic Artists: Rico Casazza, 90z, Thomas Tesla, Daniel Neighbour", location: 'Prague, Czech Republic' },
  { date: '2022-02-19', event: 'Republic Artists: Rico Casazza, Thomas Tesla, Daniel Neighbour, Asi, Unjack, Ezwell, Mark', location: 'Prague, Czech Republic' },
  { date: '2021-12-31', event: 'NYE Macrave 2021', location: 'Prague, Czech Republic' },
  { date: '2021-10-23', event: 'Republic Artists: Rico Casazza, Kozber, Silhouette, Thomas Tesla, Sammy Boyko, Shiloff', location: 'Prague, Czech Republic' },
  { date: '2021-07-31', event: 'Republic Artists: Rico Casazza, Thomas Tesla, Lucas Hulan, Encore Techno', location: 'Prague, Czech Republic' },
  { date: '2021-06-16', event: 'Gram Records 4th Anniversary', location: 'Prague, Czech Republic' },
  { date: '2020-07-25', event: 'RA: SY, Rico Casazza, Dmit.RY, Kirill Astra, Lucas Hulan, Riki Boro, Thomas Tesla', location: 'Prague, Czech Republic' },
  { date: '2020-07-25', event: 'OM', location: 'Prague, Czech Republic' },
  { date: '2020-03-20', event: 'Dionysian Mysteries presents Norwell, Neud Photo, Rico Casazza, Buzz Kill', location: 'Switzerland' },
  { date: '2019-11-22', event: "Kris 'R'US", location: 'London, UK' },
  { date: '2019-09-07', event: 'Republic Artists with Rico Casazza, Ly Sas, Lucas Hulan, Thomas Tesla', location: 'Prague, Czech Republic' },
  { date: '2019-09-07', event: 'Republic Artists Boat Party and Afterparty: Rico Casazza, Kirill Astra, Thomas Tesla', location: 'Prague, Czech Republic' },
  { date: '2019-07-26', event: 'LL016 Vapor Pad Remixes V/A — Release Party', location: 'London, UK' },
  { date: '2019-04-13', event: 'Record Store Day', location: 'London, UK' },
  { date: '2019-04-05', event: 'DT Pres. P!L rec 3rd B-Day', location: 'Poznan, Poland' },
  { date: '2018-10-14', event: "A'mas — October 2018", location: 'London, UK' },
  { date: '2018-01-26', event: 'ANA.Lock', location: 'Prague, Czech Republic' },
  { date: '2018-01-26', event: 'Beef Records In-Store Session with Rico Casazza & Schwa', location: 'Prague, Czech Republic' },
  { date: '2017-12-16', event: '199radio Christmas Party', location: 'London, UK' },
  { date: '2017-12-07', event: 'PLAY !T LOUD', location: 'London, UK' },
  { date: '2017-12-03', event: "A'mas", location: 'London, UK' },
  { date: '2017-11-15', event: 'Jonas Reinhardt, Dilian, Bell Curve DJ Sets', location: 'New York City, USA' },
  { date: '2017-09-28', event: 'LL012 Release Party', location: 'London, UK' },
  { date: '2017-06-02', event: 'Operator X Variance X Loose Lips: Variance 019 — EP Launch', location: 'Dublin, Ireland' },
  { date: '2017-05-27', event: '204 Delay', location: 'London, UK' },
  { date: '2017-04-30', event: "A'mas", location: 'London, UK' },
  { date: '2017-03-25', event: 'P!L Pres. Rico Casazza', location: 'Poznan, Poland' },
  { date: '2017-03-03', event: 'Parallel Dimensions with Pete Heller & Terry Farley', location: 'Bristol, UK' },
  { date: '2017-01-29', event: 'Meetup and The Docks Studios', location: 'London, UK' },
  { date: '2016-12-23', event: 'Tupa Tupa — Family Techno Christmas', location: 'London, UK' },
  { date: '2016-11-18', event: 'Little Beat Birthday', location: 'London, UK' },
  { date: '2016-09-23', event: "ON-SET Pure Techno Edition with D'arcangelo", location: 'London, UK' },
  { date: '2016-09-09', event: 'Tempest — with Rico Casazza (Live)', location: 'London, UK' },
  { date: '2016-06-19', event: 'Shibboleth Afterhours', location: 'London, UK' },
  { date: '2016-06-03', event: 'Little Bedroom with Rico Casazza', location: 'London, UK' },
  { date: '2016-05-08', event: 'Breakfast with Rico Casazza, D.Core & Francesco Boffa', location: 'London, UK' },
  { date: '2015-08-02', event: 'WetYourSelf! With... Jamma & Max', location: 'London, UK' },
  { date: '2015-05-08', event: 'Time Feat. Rico Casazza, La Gosse, Tristan Debroise & Anthony Segree', location: 'London, UK' },
  { date: '2015-04-17', event: 'Techno Sessions vs Underground Attack', location: 'London, UK' },
  { date: '2015-03-28', event: '7 Years of Bread & Butter with Christian Burkhardt, Rico Casazza, Jamma & Max', location: 'London, UK' },
  { date: '2015-02-06', event: 'Techno Sessions Invite Enjoy! & Treem Records', location: 'London, UK' },
  { date: '2015-01-30', event: 'LBD', location: 'London, UK' },
  { date: '2014-11-01', event: 'Circle On Tour', location: 'Czech Republic' },
  { date: '2014-10-31', event: 'Circle', location: 'Prague, Czech Republic' },
  { date: '2014-10-25', event: 'Hard Roots', location: 'London, UK' },
  { date: '2014-05-02', event: 'Ninezeronine Avec: Rico Casazza, Philippos N, Marvel', location: 'London, UK' },
  { date: '2014-04-18', event: 'Play !T Loud 3rd B-Day Smash', location: 'Poznan, Poland' },
  { date: '2014-04-04', event: 'Ninezeronine Avec: Rico Casazza, Daniel Poli', location: 'London, UK' },
  { date: '2014-03-07', event: 'Ninezeronine Avec: Rico Casazza, Nick Maleedy, Suso Flores', location: 'London, UK' },
  { date: '2014-02-13', event: 'OM with Rico Casazza', location: 'London, UK' },
  { date: '2014-01-19', event: 'Conclave with Cesare vs Disorder', location: 'London, UK' },
  { date: '2013-11-29', event: 'Hard Roots Meets Afrobeat', location: 'London, UK' },
  { date: '2013-11-15', event: 'Ninezeronine Avec Rico Casazza, Andi Parlogea & Adam Merten', location: 'London, UK' },
  { date: '2013-10-26', event: "Cartuli's Day // Halloween", location: 'London, UK' },
  { date: '2013-10-18', event: 'Ninezeronine Avec: Daniel Poli, Maryam Bash, Layladielay, Rico Casazza', location: 'London, UK' },
  { date: '2013-10-12', event: 'P!L Pres. Release Sustain London', location: 'Poznan, Poland' },
  { date: '2013-10-11', event: 'Chapeau Klack (mk 94)', location: 'Berlin, Germany' },
  { date: '2013-10-06', event: 'WetYourSelf! With... Rico Casazza (Live) & Peter Glasspool', location: 'London, UK' },
  { date: '2013-09-13', event: 'Ninezeronine', location: 'London, UK' },
  { date: '2013-08-09', event: 'Ninezeronine Avec: Rico Casazza, Loren Heer & Bastille', location: 'London, UK' },
  { date: '2013-07-26', event: 'Ninezeronine Avec: KP Sessions, Rico Casazza', location: 'London, UK' },
  { date: '2013-06-28', event: 'Meoko Project with Valentino Kanzyani, Jun Akimoto, Binh', location: 'London, UK' },
  { date: '2013-06-14', event: 'Ninezeronine with Jag Kiranmay and Rob Smile', location: 'London, UK' },
  { date: '2013-06-06', event: 'Echo Festival 2013', location: 'Croatia' },
  { date: '2013-05-26', event: "Cartuli's Day // Bank Holiday with Tevo Howard Live, Le Loup + Many More", location: 'London, UK' },
  { date: '2013-05-26', event: 'Residents / Round 2', location: 'London, UK' },
  { date: '2013-05-04', event: 'Two Spoons', location: 'London, UK' },
  { date: '2013-04-20', event: 'Housing Benefits', location: 'London, UK' },
  { date: '2013-03-15', event: 'Rework presents... Kozo, Rico Casazza (Live), Loren Heer & Bastille', location: 'London, UK' },
  { date: '2013-03-09', event: 'Fusion', location: 'Czech Republic' },
  { date: '2013-03-08', event: 'Deeper Vibe with Rico Casazza', location: 'Czech Republic' },
  { date: '2013-02-23', event: 'Greyhound with Rico Casazza', location: 'London, UK' },
  { date: '2013-02-08', event: 'Ninezeronine', location: 'London, UK' },
  { date: '2013-01-25', event: "Junktion presents Carlo, Rico Casazza, 'Moreon", location: 'London, UK' },
  { date: '2012-11-16', event: "Soundbar Rec Pres. Guillaume & The Coutu Dumonts Live 'Twice Around The Sun' Album Release Tour", location: 'Warsaw, Poland' },
  { date: '2012-11-03', event: "Cartuli's Day / 3rd Anniversary", location: 'London, UK' },
  { date: '2012-10-14', event: 'WetYourSelf! With... Rico Casazza (Live) & Kozber', location: 'London, UK' },
  { date: '2012-07-13', event: 'Ninezeronine Avec: Rico Casazza, Adam Merten', location: 'London, UK' },
  { date: '2012-07-01', event: 'Static presents Rico Casazza & Ben Rourke', location: 'London, UK' },
  { date: '2012-06-29', event: 'Hello Sunshine', location: 'London, UK' },
  { date: '2012-06-10', event: 'Jaded with Rico Casazza', location: 'London, UK' },
  { date: '2012-06-03', event: 'Twin Sister 24 Hour Sunday', location: 'London, UK' },
  { date: '2012-05-11', event: 'Ninezeronine Avec: Rico Casazza, Marvel', location: 'London, UK' },
  { date: '2012-04-13', event: 'Ninezeronine Avec: Rico Casazza, Maryam Bash', location: 'London, UK' },
  { date: '2012-03-09', event: 'Ninezeronine Avec: Rico Casazza, Maryam Bash, Lexithimie', location: 'London, UK' },
  { date: '2012-02-18', event: "No Gravity: Italiano Tsyk'A'Delizioso", location: 'Poland' },
  { date: '2012-02-10', event: 'Ninezeronine Avec: Rico Casazza, Gabor, Oli_n', location: 'London, UK' },
  { date: '2011-12-09', event: 'Ninezeronine Avec Rico Casazza & Maryam Bash', location: 'London, UK' },
  { date: '2011-11-20', event: 'Jaded with Doubtingthomas and Rico Casazza', location: 'London, UK' },
  { date: '2011-11-11', event: 'Ninezeronine Avec: Rico Casazza, Luke Black, Philippos N', location: 'London, UK' },
  { date: '2011-11-05', event: "Cartuli's Day 2º Anniversary", location: 'London, UK' },
  { date: '2011-10-14', event: 'Ninezeronine', location: 'London, UK' },
  { date: '2011-10-08', event: 'While The Iron Melts', location: 'London, UK' },
  { date: '2011-09-17', event: 'Brick Lane Music Festival 2011', location: 'London, UK' },
  { date: '2011-07-28', event: 'Brickbeat', location: 'London, UK' },
  { date: '2011-07-10', event: 'Sunset Parade', location: 'Porto, Portugal' },
  { date: '2011-07-09', event: 'Brickbeat London Apresenta Maceo Plex', location: 'Porto, Portugal' },
  { date: '2011-06-18', event: 'Syncronized presents Rico Casazza (Live)', location: 'London, UK' },
  { date: '2011-06-17', event: 'Maschine Friendly', location: 'London, UK' },
  { date: '2011-04-15', event: 'Ninezeronine', location: 'London, UK' },
  { date: '2011-03-26', event: 'While The Iron Melts', location: 'London, UK' },
  { date: '2011-02-26', event: 'So-Up Musik Showcase — Together', location: 'London, UK' },
  { date: '2011-02-19', event: "Cartuli's Day", location: 'London, UK' },
  { date: '2011-02-11', event: 'Visitor', location: 'London, UK' },
  { date: '2011-01-30', event: 'The Sunday Session', location: 'London, UK' },
  { date: '2011-01-15', event: 'The Birthday Session', location: 'London, UK' },
  { date: '2011-01-01', event: 'Nyd After Party', location: 'London, UK' },
  { date: '2010-12-19', event: 'Apparel Label Night', location: 'London, UK' },
  { date: '2010-12-10', event: 'N.I.N.E.Z.E.R.O.N.I.N.E', location: 'London, UK' },
  { date: '2010-11-30', event: '6º Aniversário Ás Prod', location: 'Porto, Portugal' },
  { date: '2010-11-21', event: 'Wetyourself with Jordi Mas & Rico Casazza (Live)', location: 'London, UK' },
  { date: '2010-10-10', event: 'Brickbeat presents Liebe*detail Showcase', location: 'London, UK' },
  { date: '2010-09-12', event: 'Hotel Fusion with James Monday', location: 'London, UK' },
  { date: '2010-08-28', event: 'Bread & Butter and Friends Free Bank Holiday Party', location: 'London, UK' },
  { date: '2010-08-15', event: 'Hotel Fusion with Doubting Thomas', location: 'London, UK' },
  { date: '2010-07-24', event: "Cartuli's Day Live Edition", location: 'London, UK' },
  { date: '2010-07-16', event: 'House Warming Party presents Special Guest Geddes', location: 'London, UK' },
  { date: '2010-06-25', event: "Elektronishe present Special Guest 'Evil' Eddie Richards", location: 'London, UK' },
  { date: '2010-06-20', event: 'Supercool', location: 'London, UK' },
  { date: '2010-06-06', event: 'Hotel Fusion', location: 'London, UK' },
  { date: '2010-05-01', event: "'While The Iron Melts…' Last Dance At Cafe", location: 'London, UK' },
  { date: '2010-04-23', event: 'Ninezeronine', location: 'London, UK' },
  { date: '2010-02-19', event: 'Audio Workout', location: 'London, UK' },
  { date: '2009-12-31', event: 'Cafe 1001 NYE 2010', location: 'London, UK' },
  { date: '2009-12-19', event: 'Late Xmas Party', location: 'London, UK' },
  { date: '2009-12-13', event: 'Show Me Your Hard Drive S.M.Y.H.D', location: 'London, UK' },
  { date: '2009-12-05', event: "Cartulis Day with Luke Solomon", location: 'London, UK' },
  { date: '2009-11-21', event: 'Siriusonic vs Refaded', location: 'London, UK' },
  { date: '2009-10-17', event: 'Clickinq vs Platinum Sound', location: 'Czech Republic' },
  { date: '2009-10-02', event: 'Imaginary Friends', location: 'London, UK' },
  { date: '2009-09-24', event: '909 Night', location: 'London, UK' },
  { date: '2009-09-18', event: 'Bounce Back', location: 'London, UK' },
  { date: '2009-09-13', event: 'Bricklane Festival', location: 'London, UK' },
  { date: '2009-07-23', event: '909 Night', location: 'London, UK' },
  { date: '2009-05-02', event: 'Series.', location: 'London, UK' },
  { date: '2009-04-30', event: '909 Night', location: 'London, UK' },
  { date: '2009-04-18', event: 'Stand Out', location: 'London, UK' },
  { date: '2009-03-26', event: 'Thursday Session', location: 'London, UK' },
  { date: '2009-03-21', event: 'Stand Out', location: 'London, UK' },
  { date: '2009-02-21', event: 'Stand Out', location: 'London, UK' },
  { date: '2008-11-29', event: 'Cerca Trova — Seek and You Will Find', location: 'London, UK' },
  { date: '2008-11-29', event: 'While The Iron Melts', location: 'London, UK' },
  { date: '2008-11-14', event: 'Kismet Night', location: 'London, UK' },
  { date: '2008-10-16', event: 'Thursday Session', location: 'London, UK' },
  { date: '2008-10-11', event: 'Stand Out', location: 'London, UK' },
  { date: '2008-09-20', event: 'Fashion Week Party', location: 'London, UK' },
  { date: '2008-08-02', event: 'Foreplay', location: 'London, UK' },
  { date: '2008-07-19', event: 'Nation Of Gondwana', location: 'Berlin, Germany' },
  { date: '2008-06-01', event: 'Insomnia Afterparty', location: 'London, UK' },
  { date: '2008-05-23', event: 'Minimal Carnival', location: 'London, UK' },
  { date: '2007-12-08', event: 'Recreation', location: 'London, UK' },
  { date: '2007-07-20', event: 'Minimal Carnival', location: 'London, UK' },
  { date: '2006-06-03', event: 'Techno Marathon', location: 'London, UK' },
];
